name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Git credentials
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config http.sslVerify false
          git config user.name "Kitty King"
          git config user.email "kitty.king@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          yarn
          yarn lerna bootstrap

      - name: Build
        run: |
          mkdir ${{ github.workspace }}/build
          echo test1 >> ${{ github.workspace }}/build/test1.txt
          echo test2 >> ${{ github.workspace }}/build/test2.txt

      - name: Create version
        run: yarn lerna version prerelease --yes

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/RELEASE.md
          files: ${{ github.workspace }}/build/**
          prerelease: true
