name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Git credentials
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config http.sslVerify false
          git config user.name "Kitty King"
          git config user.email "kitty.king@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          yarn
          yarn lerna bootstrap

      - name: Build
        run: |
          mkdir ${{ github.workspace }}/build
          echo test1 >> ${{ github.workspace }}/build/test1.txt
          echo test2 >> ${{ github.workspace }}/build/test2.txt
          tar -czvf ${{ github.workspace }}/build.tar.gz ${{ github.workspace }}/build

      - name: Create version
        run: yarn lerna version prerelease --yes

      - name: Retrieve release version
        run: |
          RELEASE_VERSION=v$(node -p 'require("./lerna.json").version')
          echo ${RELEASE_VERSION}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Remove first line of release notes
        run: tail -n +2 ${{ github.workspace }}/RELEASE.md > ${{ github.workspace }}/RELEASE.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: ${{ github.workspace }}/RELEASE.md
          files: ${{ github.workspace }}/build.tar.gz
          prerelease: true
